version: '3.0'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce
    restart: unless-stopped
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../services_data/portainer_data:/data
    ports:
      - "9000:9000"
# --------------------------------------------------------------------------- #
# Logging
# --------------------------------------------------------------------------- #
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"