version: '3.0'
services:
  node-red:
    image: nodered/node-red:2.1.4-1
    user: "${MYUID}:${MYGID}"
    environment:
      TZ: "America/Sao_Paulo"
      DOCKER_USER: "${USER}"
    ports:
      - "1880:1880"
    volumes:
      - ../services_data/node-red-data:/data
# --------------------------------------------------------------------------- #
# Logging
# --------------------------------------------------------------------------- #
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"