version: "3.0"
services:
  codeserver:
    build:
      context: ../services/code
      dockerfile: ${DOCKER_FILE:-Dockerfile}
    container_name: code
    volumes:
      - "/home/${USER}/Documents/repos:/home/coder/code-server"
      - "${PWD}/services_settings/code/settings.json:/root/.local/share/code-server/User/settings.json"
      - "${PWD}/services_settings/code/keybindings.json:/root/.local/share/code-server/User/keybindings.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    #     - "${PWD}/.config:/home/coder/.config"
    user: "${MYUID}:${MYGID}"
    environment:
      PASSWORD: password
    ports:
      - "8989:8080"
    command: code-server --disable-telemetry --cert
    restart: unless-stopped
    # ----------------------------------------------------------------------- #
    # Logging
    # ----------------------------------------------------------------------- #
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
