version: "3.0"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - "${PWD}/services_data/heimdall/config:/config"
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
