version: '3.0'
services:
  node-red:
    image: nodered/node-red:2.1.4-1
    user: "${MYUID}:${MYGID}"
    environment:
      TZ: "America/Sao_Paulo"
      DOCKER_USER: "${USER}"
    ports:
      - "1880:1880"
    volumes:
      - ../data/node-red-data:/data