version: "3.0"
services:
  jupyter-lab:
    build:
      context: ../services/jupyter
      dockerfile: ${DOCKER_FILE:-Dockerfile}
    volumes:
      - "/home/${USER}/Documents/repos/notebooks:/home/lab/nbs"
    ports:
      - 8888:8888
    restart: unless-stopped
    command: jupyter lab --no-browser --allow-root --port=8888
# --------------------------------------------------------------------------- #
# Logging
# --------------------------------------------------------------------------- #
    logging:
      driver: "json-file"
      options:
        max-size: "1k"
        max-file: "3"
